language: php
php:
  - 5.4
branches:
  only:
    - master
env:
  - FEDORA_VERSION="3.6.2"
before_install:
  - cd $HOME
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - git clone -b master git://github.com/ajstanley/islandora_porcus.git
  - export ISLANDORA_DIR=$HOME/islandora
  - $HOME/islandora/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/islandora_piggyback
  - drush en --yes islandora_piggyback
script:
  - ant -buildfile sites/all/modules/islandora_piggyback/build.xml lint
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh sites/all/modules/islandora_piggyback
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora_piggyback
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/islandora_piggyback
